###
GET http://localhost:3001/allProducts
Content-Type: application/json


###
POST http://localhost:3001/addProduct
Authorization: token
Content-Type: application/json

{
    "username": "vito",
    "nomeproduto": "pepsi",
    "preco": "5.00",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTExNzEzNTMsImV4cCI6MTY1MTIxNDU1M30.9M2jmtMXHnvJuAhBSG6fI0DUFvcqqRhJZD3ecA5IRxk"
}

###

DELETE http://localhost:3001/deleteproduct
Content-Type:application/json

{
    "nomeproduto": "pepsi",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTExODA1NTQsImV4cCI6MTY1MTIyMzc1NH0.MhJMuayag6_jQ29WhOPCTnPXU8grhHQuimR25Hui4WI"
}