###
GET http://localhost:3001/allProducts
Content-Type: application/json


###
POST http://localhost:3001/addProduct
Authorization: token
Content-Type: application/json

{
    "username": "vito",
    "nomeproduto": "pepsi",
    "preco": "5.00",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTExNzEzNTMsImV4cCI6MTY1MTIxNDU1M30.9M2jmtMXHnvJuAhBSG6fI0DUFvcqqRhJZD3ecA5IRxk"
}

###

DELETE http://localhost:3001/deleteProduct
Content-Type:application/json

{
    "nomeproduto": "undefined",
     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTM2ODE3OTIsImV4cCI6MTY1MzcyNDk5Mn0.Czq897kkmI000yrT-9DA8c4UpK9EC6oWHWRMU2wGiig"
}

###
POST http://localhost:3001/editarPrecoProduto
Content-Type: application/json

{
    "preco": "",
    "token": ""
}