###
GET http://localhost:3001/todasComandas
Content-Type: application/json


###
GET http://localhost:3001/todosClientesAbertos
Content-Type: application/json


###
GET http://localhost:3001/todasComandasAbertas
Content-Type: application/json

###

POST http://localhost:3001/addToComanda
Content-Type: application/json
 
 {
    "nomeproduto": "coca cola",
    "quantidade": 1,
    "preco" : 5.00,
    "cliente": "emari s2",
       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTIwNzIyNzcsImV4cCI6MTY1MjExNTQ3N30.SAl2LW9Ulp0v8LCvj6cpL-rTQf2dRVDv87QnBLGdVsA"
 }

###

DELETE http://localhost:3001/deletePedido
Content-Type:application/json

{
    "idpedido": 22,
     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTEyNjc5MjYsImV4cCI6MTY1MTMxMTEyNn0.Ue-2cBtPl-HqXnXgJVQclSlJNa6dOn7S-kWkBGM9rcw"
}

###
GET http://localhost:3001/comandaCliente
Content-Type: application/json

{
    "cliente" : "vitor"
     
}

###
POST http://localhost:3001/encerrarComanda
Content-Type: application/json

{
    "cliente" : "joao",
    "pagamento": "dinheiro",
     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTEyNjc5MjYsImV4cCI6MTY1MTMxMTEyNn0.Ue-2cBtPl-HqXnXgJVQclSlJNa6dOn7S-kWkBGM9rcw"       

}