###
GET http://localhost:3001/todasComandas
Content-Type: application/json


###
GET http://localhost:3001/todosClientesAbertos
Content-Type: application/json


###
GET http://localhost:3001/todasComandasAbertas
Content-Type: application/json

###

POST http://localhost:3001/addToComanda
Content-Type: application/json
 
 {
    "nomeproduto": "coca cola",
    "quantidade": 3,
    "preco" : 5.00,
    "cliente": "lu",
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzNdLCJpYXQiOjE2NTI2NjMwNTYsImV4cCI6MTY1MjcwNjI1Nn0.IWzUlWaaxYpRD5CnJUTDsGXjJR-wiXAXsSwA6somXkc"
}


###

DELETE http://localhost:3001/deletePedido
Content-Type:application/json

{
    "idpedido": 43,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzNdLCJpYXQiOjE2NTI2NjY2MTEsImV4cCI6MTY1MjcwOTgxMX0.v34ZNJvw1Il1R-nvkhrTDMV0rCPp_zDy81S319EHq6g"
}

###
GET http://localhost:3001/comandaCliente
Content-Type: application/json

{
    "cliente" : "vitor"
     
}

###
POST http://localhost:3001/encerrarComanda
Content-Type: application/json

{
    "cliente" : "joao",
    "pagamento": "dinheiro",
     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6WzFdLCJpYXQiOjE2NTEyNjc5MjYsImV4cCI6MTY1MTMxMTEyNn0.Ue-2cBtPl-HqXnXgJVQclSlJNa6dOn7S-kWkBGM9rcw"       

}